export const themeStyles = {
  default: {
    primaryLight: "#59a6f0",
    primaryDark: "#258AEA",
    secondaryLight: "#ededed",
    secondaryDark: "rgb(38, 38, 38)",
    lightText: "#fff",
    darkText: "#000",
    lightBackground: "#fff",
    darkBackground: "#000",
    // darkBackground: "rgb(25, 25, 25)",
    secondaryLightBackground: "#eeefff",
    secondaryDarkBackground: "#111",
    lightBorder: "rgb(214, 214, 214)",
    darkBorder: "rgb(34, 34, 34)",
    lightInput: "#aaa",
    darkInput: "#333",
    textHighlight: "#ffa500",
    // placeholderText: "#999",
  },
  red: {
    primaryLight: "#ff5e5e",
    primaryDark: "#ed1111",
    secondaryLight: "#ededed",
    secondaryDark: "rgb(38, 38, 38)",
    lightText: "#fff",
    darkText: "#000",
    lightBackground: "#fff",
    darkBackground: "#000",
    // darkBackground: "rgb(25, 25, 25)",
    secondaryLightBackground: "#eeefff",
    secondaryDarkBackground: "#111",
    lightBorder: "rgb(214, 214, 214)",
    darkBorder: "rgb(34, 34, 34)",
    lightInput: "#c94a4a",
    darkInput: "#822626",
    textHighlight: "#ffa500",
    // placeholderText: "#999",
  },
  pink: {
    primaryLight: "#ffc0cb",
    primaryDark: "#ff7B9C",
    secondaryLight: "#eac5d8",
    secondaryDark: "#895479",
    lightText: "#fff",
    darkText: "#222",
    lightBackground: "#fff",
    darkBackground: "#000",
    // darkBackground: "rgb(25, 25, 25)",
    secondaryLightBackground: "#eeefff",
    secondaryDarkBackground: "#111",
    lightBorder: "rgb(214, 214, 214)",
    darkBorder: "rgb(34, 34, 34)",
    lightInput: "#895479",
    darkInput: "#895479",
    textHighlight: "#ffa500",
    // placeholderText: "#999",
  },
  orange: {
    primaryLight: "#ffc200",
    primaryDark: "#ffa500",
    secondaryLight: "#f2b950",
    secondaryDark: "#b07403",
    lightText: "#fff",
    darkText: "#fff",
    lightBackground: "#fff",
    darkBackground: "#000",
    // darkBackground: "rgb(25, 25, 25)",
    secondaryLightBackground: "#eeefff",
    secondaryDarkBackground: "#111",
    lightBorder: "rgb(214, 214, 214)",
    darkBorder: "rgb(34, 34, 34)",
    lightInput: "#a14038",
    darkInput: "#6e2b25",
    textHighlight: "#ffa500",
    // placeholderText: "#999",
  },
  // "light blue": {
  //   primaryLight: "#00d6ff",
  //   primaryDark: "#00d6ff",
  //   secondaryLight: "#ffe153",
  //   secondaryDark: "#c9a800", //f4cf12
  //   lightText: "#fff",
  //   darkText: "#000",
  //   // lightBackground: "#f2aed2",
  //   // lightBackground: "#eac5d8",
  //   lightBackground: "#fff",
  //   // darkBackground: "#8c5a75",
  //   darkBackground: "#000",
  //   // darkBackground: "rgb(25, 25, 25)",
  //   secondaryLightBackground: "#eeefff",
  //   secondaryDarkBackground: "#111",
  //   lightBorder: "#d498b8",
  //   darkBorder: "#7a4d66",
  //   lightInput: "#81ddee",
  //   darkInput: "#309cb0",
  //   textHighlight: "#ffa500",
  //   // placeholderText: "#999",
  // },
};

export const getThemeStyles = (theme) => {
  return themeStyles[theme] || themeStyles.default;
};

export const themeStylesList = [
  "default",
  "red",
  "pink",
  "orange",
  // "light blue",
];
